name: Update README with Giphy

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Fetch GIF from Giphy
        env:
          GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
        run: |
          response=$(curl -s "https://api.giphy.com/v1/gifs/random?api_key=$GIPHY_API_KEY&tag=cute&rating=g")
          gif_url=$(echo $response | jq -r '.data.images.original.url')
          echo "![Cute GIF]($gif_url)" > gif.md

      - name: Update README
        run: |
          cat gif.md > README.md
          
      - name: Commit changes
        run: |
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with new GIF"
          git push

      - name: Install jq
        run: sudo apt-get install jq

