name: Update Commit History and Generate Animation

on:
  # 매일 자정에 실행
  schedule:
    - cron: '0 0 * * *'
  
  # 수동으로 실행 가능
  workflow_dispatch:
  
  # master 브랜치에 푸시될 때 실행
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Fetch commit history
        run: |
          commits=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits")
          echo "# Commit History" > commit_history.md
          echo "$commits" | jq -r '.[0:5] | .[] | "- " + .commit.message' >> commit_history.md

      - name: Add Gitanimals Image to README
        run: |
          echo '<div align="center">' > gitanimals.md
          echo '' >> gitanimals.md
          echo '<a href="https://github.com/devxb/gitanimals">' >> gitanimals.md
          echo '  <img src="https://render.gitanimals.org/farms/alswooy"/>' >> gitanimals.md
          echo '</a>' >> gitanimals.md
          echo '</div>' >> gitanimals.md
          echo '' >> gitanimals.md

      - name: Generate alswooy's github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: alswooy
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Add Contribution Grid Snake Animation to README
        run: |
          echo "![Contribution Grid Snake](dist/github-contribution-grid-snake.svg)" > snake.md

      - name: Update README
        run: |
          cat gitanimals.md commit_history.md snake.md > README.md

      - name: Configure Git
        run: |
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ghp_${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git commit -m "Update README"
          git push origin main
