name: Update Commit History in README

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Fetch commit history
        run: |
          commits=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits")
          echo "# Commit History" > commit_history.md
          echo "$commits" | jq -r '.[0:5] | .[] | "- " + .commit.message' >> commit_history.md

      - name: Add Gitanimals Image to README
        run: |
          echo '<div align="center">' > gitanimals.md
          echo '' >> gitanimals.md
          echo '<a href="https://github.com/devxb/gitanimals">' >> gitanimals.md
          echo '  <img src="https://render.gitanimals.org/farms/${{ github.repository }"/>' >> gitanimals.md
          echo '</a>' >> gitanimals.md
          echo '</div>' >> gitanimals.md
          echo '' >> gitanimals.md

      - name: Update README
        run: |
          cat gitanimals.md commit_history.md > README.md

      - name: Commit changes
        run: |
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git add README.md
          git commit -m "Update commit history and add Gitanimals image in README"
          git push
